// Original sample content only; no network requests to the member website.
const http=require('node:http'), fs=require('node:fs'), path=require('node:path');
const {article,chapters,tnm}=require('../tests/reader.cjs');
const root=path.resolve(__dirname,'..'),port=8765;
const baseCSS=`*{box-sizing:border-box}body{margin:0;font:14px/1.55 Arial,sans-serif;color:#243342;background:#f5f7f8}app-chaptercontent{display:block}.row{display:flex;margin:0 -12px}.container-fluid{padding:0 12px}#bookapproot{overflow-x:hidden}.contentDesign{padding:20px 30px;background:#174a70;color:white}.col-sm-2{width:16.66%}.col-sm-8{width:66.66%}.chapcon-nav-tabs{list-style:none;padding:0}.chapcon-nav-tabs a{display:block}h4{margin:0}.modal{display:none}dl{margin:24px 0}.sample{background:#e8f0f5;border-bottom:1px solid #c6d9e4;padding:12px 28px;font-size:13px;display:flex;align-items:center;justify-content:space-between;gap:20px}.sample strong{display:block;color:#174a70}.sample a{color:#205b85;margin-left:20px}.breadcrumb{list-style:none;padding:0}.footer-content{padding:20px}.settings{display:grid;grid-template-columns:1fr 358px;gap:70px;max-width:980px;margin:48px auto}.settings h1{font-size:42px;line-height:1.15;color:#174a70}.settings p{font-size:19px;line-height:1.7}.settings iframe{width:358px;height:680px;border:1px solid #dce4e8;border-radius:12px;background:#f7f9fa}.eyebrow{letter-spacing:2px;font-size:12px!important;font-weight:bold;color:#205b85}`;
const para='<p>This is original sample text created to demonstrate the reading layout. It is not an excerpt from a book and contains no medical guidance. Paragraphs, emphasis, and links remain in their original order.</p>';
const body=article({title:'A clearer reading experience',media:false,sections:[
 ['1','Overview','<p>Keep your place in a long article. Adjust the reading layout to suit your screen while preserving the original content.</p>'+para],
 ['2','Reading preferences','<span role="heading" aria-level="5">Text size and width</span><p>Choose a comfortable text size without changing the maximum reading width. Adjust width separately when you want longer or shorter lines.</p><h5>Line spacing</h5><p>Set the space between lines independently. Use the popup to restore the defaults or turn the reading layout off.</p>'],
 ['3','Section navigation','<p>Use the outline to jump to existing headings. On a wide screen it stays in view as you read. Long outlines can be opened in groups.</p>'+para],
 ['4','Tables and figures','<p>Captions, footnotes, links, and table relationships stay in place. Wide data tables scroll within the article.</p>'+tnm],
 ['5','Local preferences',para.repeat(3)]
]}).replace('<div class="contentDesign">','<div class="navbar row contentDesign">').replace('Original breadcrumb','Sample volume / Sample article').replace(/<span title="Add To My Favourite"><img src="\/assets\/favourite.png"><\/span>/,'').replace('Original author','Sample contributor');
const sourceReset='<style>.description[data-source] p[data-source]{margin:0!important;font-size:14px!important;line-height:1!important}</style>';
const banner='<div class="sample"><div><strong>Blue Books Reader · Unofficial</strong>Sample content for demonstration — not WHO/IARC book content.</div><nav><a href="/chaptercontent/72/19">Reading layout</a><a href="/settings">Settings</a><a href="/chapters/72">Chapters</a></nav></div>';
const mock=`window.chrome={storage:{local:{get:(k,cb)=>{const leading=Number(new URLSearchParams(location.search).get("leading"));cb({readerPrefs:{leading:leading>=1.5&&leading<=1.9?leading:1.7}});},set:async()=>{}},onChanged:{addListener:()=>{}}}};`;
const pages={'/chaptercontent/72/19':body,'/chapters/72':chapters().replace('<app-chapter>','<app-chapter><ul><li>Sample volume <span class="accordion-book-toggle"></span></li>').replace('</app-chapter>','</ul></app-chapter>')};
http.createServer((req,res)=>{
 const route=new URL(req.url,'http://127.0.0.1:'+port).pathname;
 const send=(type,data)=>{res.setHeader('Content-Type',type);res.end(data);};
 if(route==='/reader.js')return send('text/javascript',fs.readFileSync(path.join(root,'reader.js'),'utf8').replace("const ORIGIN = 'https://tumourclassification.iarc.who.int';","const ORIGIN = 'http://127.0.0.1:"+port+"';"));
 if(route==='/mock.js')return send('text/javascript',mock);
 if(['/reader.css','/popup.css','/popup.js'].includes(route))return send(route.endsWith('.css')?'text/css':'text/javascript',fs.readFileSync(path.join(root,route.slice(1))));
 if(route==='/popup.html')return send('text/html; charset=utf-8',fs.readFileSync(path.join(root,'popup.html'),'utf8').replace('<script src="popup.js">','<script src="/mock.js"></script><script src="popup.js">'));
 if(route==='/settings')return send('text/html; charset=utf-8','<!doctype html><html lang="en"><head><title>Blue Books Reader — sample settings</title><style>'+baseCSS+'</style></head><body>'+banner+'<main class="settings"><section><p class="eyebrow">YOUR READING PREFERENCES</p><h1>Set your own<br>reading rhythm.</h1><p>Text size.<br>Text width.<br>Line spacing.</p><p>Three independent controls.<br>One original source.</p><p style="font-size:14px">The actual extension popup is shown on the right.<br>This local sample does not access the member website.</p></section><iframe title="Extension settings" src="/popup.html"></iframe></main></body></html>');
 if(!pages[route]){res.writeHead(404);return res.end('Not found');}
 send('text/html; charset=utf-8','<!doctype html><html lang="en"><head><title>Blue Books Reader — sample content</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+baseCSS+'</style><link rel="stylesheet" href="/reader.css"></head><body>'+banner+'<div id="bookapproot">'+pages[route].replaceAll('class="description"','class="description" data-source').replaceAll('<p id=','<p data-source id=')+sourceReset+'<footer id="footer"><div class="row footer-content">Original synthetic content. No publisher material is included.</div></footer></div><script src="/mock.js"></script><script src="/reader.js"></script></body></html>');
}).listen(port,'127.0.0.1',()=>console.log('Synthetic demo: http://127.0.0.1:'+port+'/chaptercontent/72/19'));
